# import_m365_findings.py
# Python script to load M365 tenant assessment findings (from m365_assessment_parsed.json)
# into CISO Assistant and map them to RequirementAssessments across all active frameworks.

import os
import sys
import json
import django
from collections import defaultdict

# Add /code to path to import django models
sys.path.append("/code")
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "ciso_assistant.settings")
django.setup()

from core.models import Perimeter, ComplianceAssessment, Evidence, EvidenceRevision, RequirementAssessment
from iam.models import Folder
from django.core.files import File

def run():
    print("[*] Starting M365 Findings Ingestion...")
    
    # 1. Check file path
    json_path = "/code/db/m365_assessment_parsed.json"
    if not os.path.exists(json_path):
        print(f"[ERROR] Parsed assessment file not found at {json_path}")
        return
        
    with open(json_path, "r", encoding="utf-8") as f:
        parsed_data = json.load(f)
        
    details = parsed_data.get("details", {})
    controls = parsed_data.get("controls", [])
    print(f"[+] Loaded {len(details)} detailed checks and {len(controls)} mapped controls.")
    
    # 2. Get root folder
    root_folder = Folder.get_root_folder()
    
    # 3. Get active perimeter
    perimeter = Perimeter.objects.filter(name="M365 Security & Compliance Audit").first()
    if not perimeter:
        print("[ERROR] Perimeter 'M365 Security & Compliance Audit' not found. Cannot proceed.")
        return
        
    # 4. Ingest/Find Evidence Object for M365 Assessment Report
    ev_report, ev_created = Evidence.objects.get_or_create(
        name="M365 Tenant Assessment Report (ankbs)",
        defaults={
            "folder": root_folder,
            "description": "Automated Microsoft 365 security and compliance assessment report generated by m365-ass tool.",
            "status": Evidence.Status.APPROVED
        }
    )
    if ev_created:
        print(f"[+] Created Evidence: {ev_report.name}")
    else:
        print(f"[+] Evidence already exists: {ev_report.name}")
        if ev_report.status != Evidence.Status.APPROVED:
            ev_report.status = Evidence.Status.APPROVED
            ev_report.save()
            
    # Attach HTML file revision if not exists
    revision = ev_report.revisions.first()
    if not revision:
        filename = "m365_assessment_report_ankbs.html"
        file_path = f"/code/db/evidences/{filename}"
        if os.path.exists(file_path):
            revision = EvidenceRevision(
                evidence=ev_report,
                version=1,
                observation="Automatisch importierter Nachweis des Tenant Assessments."
            )
            with open(file_path, "rb") as f:
                revision.attachment.save(filename, File(f), save=True)
            print(f"    [+] Ingested file attachment: {filename}")
        else:
            print(f"    [WARNING] HTML report file not found at: {file_path}")
    else:
        print("    [+] HTML report attachment revision already exists.")
        
    # 5. Group checks by base ID (e.g. CA-DEVICE-002.1 -> CA-DEVICE-002)
    grouped_checks = defaultdict(list)
    for check_id, check_info in details.items():
        base_id = check_id.split(".")[0]
        grouped_checks[base_id].append({
            "check_id": check_id,
            "status": check_info.get("status", "Fail"),
            "setting": check_info.get("setting", ""),
            "category": check_info.get("category", ""),
            "current_value": check_info.get("current_value", ""),
            "recommended_value": check_info.get("recommended_value", ""),
            "remediation": check_info.get("remediation", "")
        })
        
    # 6. Map to M365-ASSESS Framework Assessments
    m365_ca = ComplianceAssessment.objects.filter(perimeter=perimeter, framework__ref_id="M365-ASSESS").first()
    if not m365_ca:
        print("[WARNING] Compliance Assessment for 'M365-ASSESS' not found. Creating it...")
        # Get framework
        from core.models import Framework
        fw = Framework.objects.filter(ref_id="M365-ASSESS").first()
        if fw:
            m365_ca = ComplianceAssessment.objects.create(
                name=f"{perimeter.name} - {fw.name}"[:250],
                perimeter=perimeter,
                framework=fw,
                folder=root_folder,
                status="active"
            )
            m365_ca.create_requirement_assessments()
        else:
            print("[ERROR] Framework 'M365-ASSESS' not found in DB. Ingest framework first.")
            return
    else:
        if m365_ca.requirement_assessments.count() == 0:
            print("[*] Creating missing requirement assessments for M365-ASSESS...")
            m365_ca.create_requirement_assessments()

    print("\n[*] Mapping findings to M365-Assess Framework requirements...")
    m365_mapped_count = 0
    m365_not_found = []
    
    for base_id, subchecks in grouped_checks.items():
        # Retrieve RequirementAssessment
        req_assess = RequirementAssessment.objects.filter(
            compliance_assessment=m365_ca,
            requirement__ref_id=base_id
        ).first()
        
        if not req_assess:
            m365_not_found.append(base_id)
            continue
            
        # Determine aggregated result
        # 'Fail' > 'Warning/Review' > 'Pass'
        has_fail = any(c["status"].lower() == "fail" for c in subchecks)
        has_warn = any(c["status"].lower() in ["warning", "review", "warn"] for c in subchecks)
        
        if has_fail:
            result = "non_compliant"
            status_label = "Fehlgeschlagen (Non-compliant)"
        elif has_warn:
            result = "partially_compliant"
            status_label = "Teilweise erfüllt / Review erforderlich (Partially compliant)"
        else:
            result = "compliant"
            status_label = "Erfolgreich bestanden (Compliant)"
            
        # Compile observation
        observation_parts = [
            f"### Automatische M365-Assess Auswertung: {status_label}",
            f"Dieser Anforderungspunkt wurde durch die Auswertung des Tenant-Assessment-Berichts bewertet.",
            "",
            "#### Detaillierte Testergebnisse:"
        ]
        
        for c in subchecks:
            icon = "❌" if c["status"].lower() == "fail" else "⚠️" if c["status"].lower() in ["warning", "review", "warn"] else "✅"
            observation_parts.extend([
                f"- **{icon} Check {c['check_id']}:** {c['setting']}",
                f"  - **Status:** {c['status']}",
                f"  - **Ist-Wert:** `{c['current_value']}`",
                f"  - **Empfehlung:** `{c['recommended_value']}`"
            ])
            if c["remediation"]:
                observation_parts.append(f"  - **PowerShell Quick-Fix (Remediation):**")
                observation_parts.append(f"    ```powershell")
                observation_parts.append(f"    {c['remediation']}")
                observation_parts.append(f"    ```")
                
        observation_text = "\n".join(observation_parts)
        
        # Save assessment
        req_assess.result = result
        req_assess.status = "done"
        req_assess.observation = observation_text
        req_assess.evidences.add(ev_report)
        req_assess.save()
        m365_mapped_count += 1
        
    print(f"[+] Successfully updated {m365_mapped_count} requirement assessments in M365-Assess.")
    if m365_not_found:
        print(f"[WARNING] {len(m365_not_found)} check IDs could not be matched to requirement nodes in M365-Assess: {m365_not_found}")
        
    # 7. Map findings to other active frameworks (ISO 27001, NIST CSF, SOC 2)
    fw_map = {
        "Iso27001": "ISO/IEC 27001:2022",
        "NistCsf": "NIST-CSF-2.0-journey",
        "Soc2": "SOC2-2017-Rev-2022"
    }
    
    fw_control_checks = defaultdict(list)
    for ctrl in controls:
        check_id = ctrl["check_id"]
        check_status = ctrl["status"]
        check_name = ctrl["name"]
        
        # Get details
        check_detail = details.get(check_id, {})
        setting = check_detail.get("setting", check_name)
        current_value = check_detail.get("current_value", "")
        recommended_value = check_detail.get("recommended_value", "")
        remediation = check_detail.get("remediation", "")
        
        for json_fw, grc_fw_ref in fw_map.items():
            if json_fw in ctrl.get("mappings", {}):
                for control_id in ctrl["mappings"][json_fw]:
                    fw_control_checks[(grc_fw_ref, control_id)].append({
                        "check_id": check_id,
                        "status": check_status,
                        "setting": setting,
                        "current_value": current_value,
                        "recommended_value": recommended_value,
                        "remediation": remediation
                    })
                    
    print("\n[*] Propagating findings to mapped frameworks (ISO 27001, NIST CSF, SOC 2)...")
    fw_mapped_count = defaultdict(int)
    fw_not_found_count = defaultdict(int)
    
    for (grc_fw_ref, control_id), subchecks in fw_control_checks.items():
        # Retrieve RequirementAssessment for this perimeter and framework
        req_assess = RequirementAssessment.objects.filter(
            compliance_assessment__perimeter=perimeter,
            compliance_assessment__framework__ref_id=grc_fw_ref,
            requirement__ref_id=control_id
        ).first()
        
        if not req_assess:
            fw_not_found_count[grc_fw_ref] += 1
            continue
            
        # Determine aggregated result
        has_fail = any(c["status"].lower() == "fail" for c in subchecks)
        has_warn = any(c["status"].lower() in ["warning", "review", "warn"] for c in subchecks)
        
        if has_fail:
            result = "non_compliant"
            status_label = "Nicht erfüllt (Non-compliant)"
        elif has_warn:
            result = "partially_compliant"
            status_label = "Teilweise erfüllt (Partially compliant)"
        else:
            result = "compliant"
            status_label = "Erfüllt (Compliant)"
            
        # Compile observation
        observation_parts = [
            f"### Automatische Audit-Validierung via M365 Tenant Assessment",
            f"Diese GRC-Anforderung wurde automatisch bewertet, da sie mit M365-Konfigurationschecks verknüpft ist.",
            f"**Aggregierter Status:** {status_label}",
            "",
            "#### Zugehörige M365 Tenant Checks:"
        ]
        
        for c in subchecks:
            icon = "❌" if c["status"].lower() == "fail" else "⚠️" if c["status"].lower() in ["warning", "review", "warn"] else "✅"
            observation_parts.extend([
                f"- **{icon} Check {c['check_id']}:** {c['setting']}",
                f"  - **Status:** {c['status']}",
                f"  - **Ist-Wert:** `{c['current_value']}`",
                f"  - **Soll-Wert:** `{c['recommended_value']}`"
            ])
            if c["remediation"]:
                observation_parts.append(f"  - **Behebung (Remediation):** `{c['remediation']}`")
                
        observation_text = "\n".join(observation_parts)
        
        # Save assessment
        req_assess.result = result
        req_assess.status = "done"
        req_assess.observation = observation_text
        req_assess.evidences.add(ev_report)
        req_assess.save()
        
        fw_mapped_count[grc_fw_ref] += 1
        
    # Print summary
    for grc_fw_ref, count in fw_mapped_count.items():
        print(f"  [+] Framework '{grc_fw_ref}': successfully mapped {count} requirements.")
        if fw_not_found_count[grc_fw_ref] > 0:
            print(f"  [.] Framework '{grc_fw_ref}': {fw_not_found_count[grc_fw_ref]} mapped control IDs not found in GRC database.")

    print("\n[+] M365 Findings Ingestion and cross-framework propagation completed successfully!")

if __name__ == "__main__":
    run()
